Update @tableland/rigs to the latest sdk
tablelandnetwork/rigs pull request #562
Opened 2023-01-23 21:54 UTC by asutula

Pretty straight forward I think, but blocked now by some upstream work on getting the sdk to properly provide a cjs distribution (https://github.com/tablelandnetwork/wasm-sqlparser/pull/91, which will be pulled into the sdk). This is required because hardhat projects like this are cjs. It's not clear to me if they can be esm or not. I tried and quickly ran into problems with hardhat loading the hardhat config file. 

Will leave this as draft for now for some early eyes.

2023-01-25 10:17 UTC, datadanne requested changes
Nice, the code changes lgtm!

We need to update the import in `ethereum/deployments.ts` as well, `@tableland/sdk` isn't exporting `ChainName`:
```
deployments.ts(1,10): error TS2305: Module '"@tableland/sdk"' has no exported member 'ChainName'.
```

2023-01-25 15:11 UTC, asutula commented
Good catch @datadanne, fixed.

2023-01-25 21:52 UTC, carsonfarmer approved these changes

2023-01-25 21:56 UTC, datadanne approved these changes

2023-01-25 22:26 UTC, merged

2023-01-26 04:23 UTC, asutula commented
Version 0.1.3 is published to npm @datadanne